org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.88
rinku_version=3.0.4

mod_id=videoscreen
mod_name=Video Screen Rinku
mod_license=All Rights Reserved
mod_version=0.2.0
mod_group_id=com.furk5nn.videoscreen
