license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
A simple local MP4 video screen with automatically merging screen blocks.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"



[[dependencies.${mod_id}]]
modId="watermedia"
type="required"
versionRange="[3.0.0.23,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="watermedia_binaries"
type="required"
versionRange="[3.0.0.6,)"
ordering="AFTER"
side="CLIENT"
